version: "3.8"

volumes:
  postgres_data:

services:
  main:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    networks:
      - default
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    ports:
      - "5000:5000"

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./env/db.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data