// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"avito-tech-task/internal/app/models"
	"avito-tech-task/internal/app/transactions"
	"sync"
)

// Ensure, that MockStorage does implement transactions.Storage.
// If this is not the case, regenerate this file with moq.
var _ transactions.Storage = &MockStorage{}

// MockStorage is a mock implementation of transactions.Storage.
//
// 	func TestSomethingThatUsesStorage(t *testing.T) {
//
// 		// make and configure a mocked transactions.Storage
// 		mockedStorage := &MockStorage{
// 			DoesUserExistFunc: func(n int64) (bool, error) {
// 				panic("mock out the DoesUserExist method")
// 			},
// 			GetUserTransactionsFunc: func(n int64, transactionsSelectionParams *models.TransactionsSelectionParams) (models.Transactions, error) {
// 				panic("mock out the GetUserTransactions method")
// 			},
// 		}
//
// 		// use mockedStorage in code that requires transactions.Storage
// 		// and then make assertions.
//
// 	}
type MockStorage struct {
	// DoesUserExistFunc mocks the DoesUserExist method.
	DoesUserExistFunc func(n int64) (bool, error)

	// GetUserTransactionsFunc mocks the GetUserTransactions method.
	GetUserTransactionsFunc func(n int64, transactionsSelectionParams *models.TransactionsSelectionParams) (models.Transactions, error)

	// calls tracks calls to the methods.
	calls struct {
		// DoesUserExist holds details about calls to the DoesUserExist method.
		DoesUserExist []struct {
			// N is the n argument value.
			N int64
		}
		// GetUserTransactions holds details about calls to the GetUserTransactions method.
		GetUserTransactions []struct {
			// N is the n argument value.
			N int64
			// TransactionsSelectionParams is the transactionsSelectionParams argument value.
			TransactionsSelectionParams *models.TransactionsSelectionParams
		}
	}
	lockDoesUserExist       sync.RWMutex
	lockGetUserTransactions sync.RWMutex
}

// DoesUserExist calls DoesUserExistFunc.
func (mock *MockStorage) DoesUserExist(n int64) (bool, error) {
	if mock.DoesUserExistFunc == nil {
		panic("MockStorage.DoesUserExistFunc: method is nil but Storage.DoesUserExist was just called")
	}
	callInfo := struct {
		N int64
	}{
		N: n,
	}
	mock.lockDoesUserExist.Lock()
	mock.calls.DoesUserExist = append(mock.calls.DoesUserExist, callInfo)
	mock.lockDoesUserExist.Unlock()
	return mock.DoesUserExistFunc(n)
}

// DoesUserExistCalls gets all the calls that were made to DoesUserExist.
// Check the length with:
//     len(mockedStorage.DoesUserExistCalls())
func (mock *MockStorage) DoesUserExistCalls() []struct {
	N int64
} {
	var calls []struct {
		N int64
	}
	mock.lockDoesUserExist.RLock()
	calls = mock.calls.DoesUserExist
	mock.lockDoesUserExist.RUnlock()
	return calls
}

// GetUserTransactions calls GetUserTransactionsFunc.
func (mock *MockStorage) GetUserTransactions(n int64, transactionsSelectionParams *models.TransactionsSelectionParams) (models.Transactions, error) {
	if mock.GetUserTransactionsFunc == nil {
		panic("MockStorage.GetUserTransactionsFunc: method is nil but Storage.GetUserTransactions was just called")
	}
	callInfo := struct {
		N                           int64
		TransactionsSelectionParams *models.TransactionsSelectionParams
	}{
		N:                           n,
		TransactionsSelectionParams: transactionsSelectionParams,
	}
	mock.lockGetUserTransactions.Lock()
	mock.calls.GetUserTransactions = append(mock.calls.GetUserTransactions, callInfo)
	mock.lockGetUserTransactions.Unlock()
	return mock.GetUserTransactionsFunc(n, transactionsSelectionParams)
}

// GetUserTransactionsCalls gets all the calls that were made to GetUserTransactions.
// Check the length with:
//     len(mockedStorage.GetUserTransactionsCalls())
func (mock *MockStorage) GetUserTransactionsCalls() []struct {
	N                           int64
	TransactionsSelectionParams *models.TransactionsSelectionParams
} {
	var calls []struct {
		N                           int64
		TransactionsSelectionParams *models.TransactionsSelectionParams
	}
	mock.lockGetUserTransactions.RLock()
	calls = mock.calls.GetUserTransactions
	mock.lockGetUserTransactions.RUnlock()
	return calls
}
